"""Initial schema

Revision ID: 172dd9c19d31
Revises: 
Create Date: 2025-12-22 14:43:55.041935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172dd9c19d31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('summary_pt', sa.Text(), nullable=False),
    sa.Column('one_line_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cleanup_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('posts_removed', sa.Integer(), nullable=True),
    sa.Column('full_content_cleared', sa.Integer(), nullable=True),
    sa.Column('summaries_cleared', sa.Integer(), nullable=True),
    sa.Column('unread_removed', sa.Integer(), nullable=True),
    sa.Column('bytes_freed', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cleanup_logs', schema=None) as batch_op:
        batch_op.create_index('idx_cleanup_executed', [sa.literal_column('executed_at DESC')], unique=False)

    op.create_table('scheduler_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.Text(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('id = 1', name='single_row_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('summary_failures', schema=None) as batch_op:
        batch_op.create_index('idx_failures_hash', ['content_hash'], unique=False)

    op.create_table('token_blacklist',
    sa.Column('jti', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index('idx_blacklist_expires', ['expires_at'], unique=False)

    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('site_url', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('disable_reason', sa.Text(), nullable=True),
    sa.Column('guid_unreliable', sa.Boolean(), nullable=True),
    sa.Column('guid_collision_count', sa.Integer(), nullable=True),
    sa.Column('allow_duplicate_urls', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('normalized_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('sort_date', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('fetch_full_attempted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('idx_posts_content_hash', ['feed_id', 'content_hash'], unique=True, sqlite_where=sa.text('content_hash IS NOT NULL AND guid IS NULL AND normalized_url IS NULL'))
        batch_op.create_index('idx_posts_feed', ['feed_id'], unique=False)
        batch_op.create_index('idx_posts_guid', ['feed_id', 'guid'], unique=True, sqlite_where=sa.text('guid IS NOT NULL'))
        batch_op.create_index('idx_posts_hash', ['content_hash'], unique=False)
        batch_op.create_index('idx_posts_read', ['is_read'], unique=False)
        batch_op.create_index('idx_posts_read_at', ['read_at'], unique=False, sqlite_where=sa.text('is_read = 1'))
        batch_op.create_index('idx_posts_sort', [sa.literal_column('sort_date DESC')], unique=False)
        batch_op.create_index('idx_posts_url', ['feed_id', 'normalized_url'], unique=True, sqlite_where=sa.text('normalized_url IS NOT NULL'))

    op.create_table('summary_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    with op.batch_alter_table('summary_queue', schema=None) as batch_op:
        batch_op.create_index('idx_queue_pending', ['locked_at', 'cooldown_until'], unique=False)
        batch_op.create_index('idx_queue_priority', [sa.literal_column('priority DESC'), 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary_queue', schema=None) as batch_op:
        batch_op.drop_index('idx_queue_priority')
        batch_op.drop_index('idx_queue_pending')

    op.drop_table('summary_queue')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('idx_posts_url', sqlite_where=sa.text('normalized_url IS NOT NULL'))
        batch_op.drop_index('idx_posts_sort')
        batch_op.drop_index('idx_posts_read_at', sqlite_where=sa.text('is_read = 1'))
        batch_op.drop_index('idx_posts_read')
        batch_op.drop_index('idx_posts_hash')
        batch_op.drop_index('idx_posts_guid', sqlite_where=sa.text('guid IS NOT NULL'))
        batch_op.drop_index('idx_posts_feed')
        batch_op.drop_index('idx_posts_content_hash', sqlite_where=sa.text('content_hash IS NOT NULL AND guid IS NULL AND normalized_url IS NULL'))

    op.drop_table('posts')
    op.drop_table('feeds')
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index('idx_blacklist_expires')

    op.drop_table('token_blacklist')
    with op.batch_alter_table('summary_failures', schema=None) as batch_op:
        batch_op.drop_index('idx_failures_hash')

    op.drop_table('summary_failures')
    op.drop_table('scheduler_lock')
    with op.batch_alter_table('cleanup_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_cleanup_executed')

    op.drop_table('cleanup_logs')
    op.drop_table('categories')
    op.drop_table('app_settings')
    op.drop_table('ai_summaries')
    # ### end Alembic commands ###
